name: Build Project
on: push

jobs:
  build-project:
    name: Build ${{ matrix.config }} for ${{ matrix.arch }}-bit architecture
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ 32, 64 ]
        config: [ Release ]
        include:
          - arch: 32
            platform: Win32
            term: amd64_x86

          - arch: 64
            platform: x64
            term: amd64
    env:
      BUILD_DIR: ${{ github.workspace }}\build\${{ matrix.arch }}
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DISABLE_METRICS: true
      DLL_FILE: EOSSDK-Win${{ matrix.arch }}-Shipping
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install and cache the latest CMake
        uses: lukka/get-cmake@latest

      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.BUILD_DIR }}\vcpkg_installed
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}\buildtrees
            !${{ env.VCPKG_ROOT }}\packages
            !${{ env.VCPKG_ROOT }}\downloads
          key: vcpkg-${{ hashFiles( 'vcpkg.json' ) }}-${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}-${{ matrix.arch }}-invalidate

      - name: Setup Developer Command Prompt for Microsoft Visual C++.
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.term }}

      - name: Restore build files from cache
        uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR }}
          key: build-${{ matrix.arch }}-${{ matrix.config }}-${{ hashFiles( 'CMakeLists.txt' ) }}

      - name: Regenerate build files
        run: cmake -G "Visual Studio 16 2019" -A ${{ matrix.platform }} -B ${{ env.BUILD_DIR }}

      - name: Build the project
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.config }}

      - name: Upload the binary file and debug info
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DLL_FILE }}-${{ matrix.config }}
          path: ${{ env.BUILD_DIR }}\${{ matrix.config }}\${{ env.DLL_FILE }}.*

  package-project:
    name: Package the artifacts into a release zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-project
    permissions:
      contents: write
    steps:
      - name: Setup version tag
        id: env_setup
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install required tools
        run: |
          sudo apt update
          sudo apt install zip tree

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Print artifact tree
        run: tree artifacts

      - name: Make release zip
        run: >
          zip -j ScreamAPI-v${{ env.VERSION_TAG }}.zip
          artifacts/EOSSDK*/*.dll
          extra/README.txt
          res/ScreamAPI.json

      - name: Create a release draft
        uses: softprops/action-gh-release@v1
        with:
          body: '# ðŸ“‘ Changelog'
          draft: true
          prerelease: false
          files: ScreamAPI-v${{ env.VERSION_TAG }}.zip
          name: Release ${{ env.VERSION_TAG }}
          tag_name: ${{ env.VERSION_TAG }}
          fail_on_unmatched_files: true

